# Default values for risk-advisor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: pposkrobko/risk-advisor
  tag: latest #TODO: change to "stable" for final release
  pullPolicy: IfNotPresent
service:
  name: risk-advisor-service
  type: NodePort
  externalPort: 11111
  internalPort: 9997
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

