apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: risk-advisor 
  labels:
   name: risk-advisor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: risk-advisor
        name: risk-advisor
    spec:
      containers:
      - name: risk-advisor
        image: pposkrobko/risk-advisor
        ports:
        - containerPort: 9997
