apiVersion: v1
kind: Pod
metadata:
  name: risk-advisor
spec:
  containers: [
    {
      name: proxy,
      image: pposkrobko/proxy,
      ports: [
        { 
          containerPort: 9999 
        },
        {
          containerPort: 9998
        }
      ]
    },
    {
      name: riskadvisor,
      image: pposkrobko/riskadvisor,
      ports: [
        { 
          containerPort: 9997 
        }
      ]
    },	
    {
      name: kube-scheduler,
      image: gcr.io/google_containers/kube-scheduler,
      ports: [
        { 
          containerPort: 10251 
        }
      ]
    }
  ]

